# Generated by Django 4.1.7 on 2023-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('monthly_marking', models.IntegerField()),
                ('custom_monthly', models.IntegerField()),
                ('pricing_monthly', models.IntegerField()),
                ('pricing_yearly', models.IntegerField()),
            ],
        ),
    ]
