# Generated by Django 4.1.7 on 2023-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='pricing_monthly',
            field=models.IntegerField(default=0),
        ),
    ]
