# Generated by Django 4.2 on 2023-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="plan",
            name="monthly_credits",
            field=models.IntegerField(default=0),
        ),
    ]
