# Generated by Django 4.2 on 2023-08-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="type",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
    ]
