# Generated by Django 4.2 on 2023-08-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_productprice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productprice",
            name="m_or_y",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
