# Generated by Django 4.2 on 2023-07-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_product_alter_plan_monthly_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_key",
            field=models.CharField(default="lala", max_length=100),
            preserve_default=False,
        ),
    ]
