# Generated by Django 4.2 on 2023-07-15 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_product_price_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
