# Generated by Django 4.2 on 2023-08-12 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_productprice_m_or_y"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plan",
        ),
    ]
