# Generated by Django 4.2 on 2023-07-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_remove_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_key",
        ),
        migrations.AddField(
            model_name="product",
            name="product_key",
            field=models.CharField(default="lala", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_key", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.product",
                    ),
                ),
            ],
        ),
    ]
