# Generated by Django 4.1.7 on 2023-04-23 22:12

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(default=accounts.models.get_default_plan, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
