# Generated by Django 4.2 on 2023-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="credits",
            field=models.IntegerField(default=0),
        ),
    ]
