# Generated by Django 4.2 on 2023-09-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_remove_nceaexam_users"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="exams",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="main.nceaexam"
            ),
        ),
    ]
