# Generated by Django 4.2 on 2023-09-30 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_exams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="exams",
        ),
    ]
