# Generated by Django 4.2 on 2023-06-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
