# Generated by Django 4.2 on 2023-08-12 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_productprice_m_or_y"),
        ("accounts", "0002_customuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.productprice",
            ),
        ),
    ]
