# Generated by Django 4.2 on 2023-12-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_exams"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="student",
            field=models.BooleanField(default=False),
        ),
    ]
