# Generated by Django 4.2 on 2024-02-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0051_markedchunks"),
        ("accounts", "0006_customuser_example_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="example_marks",
            field=models.ManyToManyField(
                blank=True, related_name="examplemark", to="main.nceauserdocument"
            ),
        ),
    ]
