# Generated by Django 4.2 on 2024-02-27 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_customuser_example_marks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="example_marks",
            new_name="example_documents",
        ),
    ]
