# Generated by Django 4.2 on 2024-03-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_example_marks_customuser_example_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tester",
            field=models.BooleanField(default=False),
        ),
    ]
