# Generated by Django 4.2 on 2023-05-03 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NceaDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mark", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NceaOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standard", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NceaTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
                ("achieved", models.TextField()),
                ("merit", models.TextField()),
                ("excellence", models.TextField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaone"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                ("n0", models.IntegerField()),
                ("a1", models.IntegerField()),
                ("n2", models.IntegerField()),
                ("a3", models.IntegerField()),
                ("a4", models.IntegerField()),
                ("m5", models.IntegerField()),
                ("m6", models.IntegerField()),
                ("e7", models.IntegerField()),
                ("e8", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaone"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
                ("text", models.TextField()),
                ("mark", models.IntegerField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceadocument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nceadocument",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.nceaone"
            ),
        ),
        migrations.AddField(
            model_name="nceadocument",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nceadocument",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
