# Generated by Django 4.2 on 2023-07-23 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NceaExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standard", models.IntegerField()),
                ("year", models.IntegerField()),
                ("exam_name", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nceaexam",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaQUESTION",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                (
                    "n0",
                    models.IntegerField(
                        choices=[
                            (1, "1a"),
                            (2, "2a"),
                            (3, "3a"),
                            (4, "4a"),
                            (5, "5a"),
                            (6, "6a"),
                            (7, "7a"),
                            (8, "8a"),
                            (9, "9a"),
                            (10, "10a"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "n1",
                    models.IntegerField(
                        choices=[
                            (1, "1a"),
                            (2, "2a"),
                            (3, "3a"),
                            (4, "4a"),
                            (5, "5a"),
                            (6, "6a"),
                            (7, "7a"),
                            (8, "8a"),
                            (9, "9a"),
                            (10, "10a"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "n2",
                    models.IntegerField(
                        choices=[
                            (1, "1a"),
                            (2, "2a"),
                            (3, "3a"),
                            (4, "4a"),
                            (5, "5a"),
                            (6, "6a"),
                            (7, "7a"),
                            (8, "8a"),
                            (9, "9a"),
                            (10, "10a"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "a3",
                    models.IntegerField(
                        choices=[
                            (1, "1a"),
                            (2, "2a"),
                            (3, "3a"),
                            (4, "4a"),
                            (5, "5a"),
                            (6, "6a"),
                            (7, "7a"),
                            (8, "8a"),
                            (9, "9a"),
                            (10, "10a"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "a4",
                    models.IntegerField(
                        choices=[
                            (1, "1a"),
                            (2, "2a"),
                            (3, "3a"),
                            (4, "4a"),
                            (5, "5a"),
                            (6, "6a"),
                            (7, "7a"),
                            (8, "8a"),
                            (9, "9a"),
                            (10, "10a"),
                        ],
                        default=4,
                    ),
                ),
                (
                    "m5",
                    models.IntegerField(
                        choices=[
                            (1, "1m"),
                            (2, "2m"),
                            (3, "3m"),
                            (4, "4m"),
                            (5, "5m"),
                            (6, "6m"),
                            (7, "7m"),
                            (8, "8m"),
                            (9, "9m"),
                            (10, "10m"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "m6",
                    models.IntegerField(
                        choices=[
                            (1, "1m"),
                            (2, "2m"),
                            (3, "3m"),
                            (4, "4m"),
                            (5, "5m"),
                            (6, "6m"),
                            (7, "7m"),
                            (8, "8m"),
                            (9, "9m"),
                            (10, "10m"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "e7",
                    models.IntegerField(
                        choices=[
                            (1, "1e"),
                            (2, "2e"),
                            (3, "3e"),
                            (4, "4e"),
                            (5, "5e"),
                            (6, "6e"),
                            (7, "7e"),
                            (8, "8e"),
                            (9, "9e"),
                            (10, "10e"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "e8",
                    models.IntegerField(
                        choices=[
                            (1, "1e"),
                            (2, "2e"),
                            (3, "3e"),
                            (4, "4e"),
                            (5, "5e"),
                            (6, "6e"),
                            (7, "7e"),
                            (8, "8e"),
                            (9, "9e"),
                            (10, "10e"),
                        ],
                        default=2,
                    ),
                ),
                ("system", models.TextField(blank=True, null=True)),
                ("system_html", models.TextField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaexam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaSecondaryQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["primary", "secondary"],
            },
        ),
        migrations.CreateModel(
            name="NceaUserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mark", models.IntegerField(default=0)),
                ("marked_before", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaexam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nceadocument",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaUserQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                ("answer_html", models.TextField(blank=True, null=True)),
                ("achievement", models.IntegerField(default=0)),
                ("merit", models.IntegerField(default=0)),
                ("excellence", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceasecondaryquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HelpMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssesmentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("n", "QUESTION"),
                            ("a", "Achieved"),
                            ("m", "Merit"),
                            ("e", "Excellence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
                (
                    "secondary_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceasecondaryquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["QUESTION", "order"],
            },
        ),
    ]
