# Generated by Django 4.2 on 2023-06-16 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NceaExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standard", models.IntegerField()),
                ("year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NceaQUESTION",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                ("n0", models.IntegerField()),
                ("n1", models.IntegerField()),
                ("n2", models.IntegerField()),
                ("a3", models.IntegerField()),
                ("a4", models.IntegerField()),
                ("m5", models.IntegerField()),
                ("m6", models.IntegerField()),
                ("e7", models.IntegerField()),
                ("e8", models.IntegerField()),
                ("system", models.TextField(blank=True, null=True)),
                ("system_html", models.TextField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaexam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaSecondaryQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["primary", "secondary"],
            },
        ),
        migrations.CreateModel(
            name="NceaUserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mark", models.IntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.nceaexam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nceadocument",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaUserQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                ("achievement", models.IntegerField(default=0)),
                ("merit", models.IntegerField(default=0)),
                ("excellence", models.IntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceasecondaryquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssesmentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["QUESTION", "order"],
            },
        ),
    ]
