# Generated by Django 4.2 on 2023-08-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nceauserdocument",
            name="credit_price",
            field=models.IntegerField(default=0),
        ),
    ]
