# Generated by Django 4.2 on 2023-05-14 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NceaQUESTION",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QUESTION", models.IntegerField()),
                ("system", models.TextField()),
                ("n0", models.IntegerField()),
                ("a1", models.IntegerField()),
                ("n2", models.IntegerField()),
                ("a3", models.IntegerField()),
                ("a4", models.IntegerField()),
                ("m5", models.IntegerField()),
                ("m6", models.IntegerField()),
                ("e7", models.IntegerField()),
                ("e8", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NceaSecondaryQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NceaUserQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Specifics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("type", models.IntegerField()),
                ("text", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="nceathree",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="nceatwo",
            name="exam",
        ),
        migrations.RenameModel(
            old_name="NceaOne",
            new_name="NceaExam",
        ),
        migrations.RenameModel(
            old_name="NceaDocument",
            new_name="NceaUserDocument",
        ),
        migrations.DeleteModel(
            name="NceaQuestions",
        ),
        migrations.DeleteModel(
            name="NceaThree",
        ),
        migrations.DeleteModel(
            name="NceaTwo",
        ),
        migrations.AddField(
            model_name="nceauserquestions",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.nceauserdocument"
            ),
        ),
        migrations.AddField(
            model_name="nceauserquestions",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.nceasecondaryquestion",
            ),
        ),
        migrations.AddField(
            model_name="nceasecondaryquestion",
            name="specifics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.specifics"
            ),
        ),
        migrations.AddField(
            model_name="nceaquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.nceaexam"
            ),
        ),
    ]
