# Generated by Django 4.2 on 2023-06-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nceauserquestions",
            name="answer_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
