# Generated by Django 4.2 on 2023-09-07 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_markingtoast"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarkingToast",
        ),
    ]
