# Generated by Django 4.2 on 2023-05-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_nceaquestion_nceasecondaryquestion_nceauserquestions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceasecondaryquestion",
            name="specifics",
        ),
        migrations.AddField(
            model_name="specifics",
            name="secondaryquestion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.nceasecondaryquestion",
            ),
        ),
    ]
