# Generated by Django 4.2 on 2023-05-14 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_nceasecondaryquestion_specifics_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nceaquestion",
            old_name="a1",
            new_name="n1",
        ),
    ]
