# Generated by Django 4.2 on 2023-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_specifics_secondaryquestion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nceasecondaryquestion",
            options={"ordering": ["primary", "secondary"]},
        ),
        migrations.AlterField(
            model_name="specifics",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
