# Generated by Django 4.2 on 2023-09-10 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_toastmessage_message_alter_toastmessage_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toastmessage",
            name="message",
        ),
        migrations.AlterField(
            model_name="toastmessage",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.nceauserdocument"
            ),
        ),
        migrations.AlterField(
            model_name="toastmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toast",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
