# Generated by Django 4.2 on 2023-09-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_toastmessage_document_alter_toastmessage_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toastmessage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="toastmessage",
            name="document",
        ),
        migrations.AddField(
            model_name="toastmessage",
            name="exam_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="toastmessage",
            name="progress",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="toastmessage",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="toastmessage",
            name="user_document_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
