# Generated by Django 4.2 on 2023-09-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_remove_toastmessage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toastmessage",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.nceauserdocument",
            ),
        ),
    ]
