# Generated by Django 4.2 on 2023-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_delete_toastmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceauserquestions",
            name="answer",
            field=models.TextField(max_length=1500),
        ),
    ]
