# Generated by Django 4.2 on 2023-09-30 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_remove_nceaexam_user_nceaexam_is_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceaexam",
            name="users",
        ),
    ]
