# Generated by Django 4.2 on 2023-10-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_nceauserdocument_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("text", models.TextField(blank=True, default=None, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
            ],
        ),
    ]
