# Generated by Django 4.2 on 2023-10-16 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_ocrimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nceaquestion",
            options={"ordering": ["exam", "QUESTION"]},
        ),
        migrations.AlterModelOptions(
            name="nceascores",
            options={"ordering": ["document", "QUESTION"]},
        ),
        migrations.AlterModelOptions(
            name="nceasecondaryquestion",
            options={"ordering": ["QUESTION", "primary", "secondary"]},
        ),
        migrations.AlterModelOptions(
            name="nceauserquestions",
            options={"ordering": ["document", "question"]},
        ),
    ]
