# Generated by Django 4.2 on 2023-10-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_nceaquestion_options_alter_nceascores_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceauserdocument",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.file",
            ),
        ),
    ]
