# Generated by Django 4.2 on 2023-10-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_alter_nceauserdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="nceasecondaryquestion",
            name="evidence",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=10)),
                (
                    "secondary_questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="nceacriteria",
                        to="main.nceasecondaryquestion",
                    ),
                ),
            ],
        ),
    ]
