# Generated by Django 4.2 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_nceasecondaryquestion_evidence_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="image",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nceasecondaryquestion",
            name="evidence",
            field=models.TextField(),
        ),
    ]
