# Generated by Django 4.2 on 2023-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_alter_nceasecondaryquestion_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
