# Generated by Django 4.2 on 2023-10-28 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_criteria_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceaquestion",
            name="system",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="system_html",
        ),
    ]
