# Generated by Django 4.2 on 2023-10-29 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_remove_nceaquestion_system_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.IntegerField(default=0)),
                ("explanation", models.TextField()),
                (
                    "criteria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="main.criteria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quoted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bullet_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_point",
                        to="main.bulletpoint",
                    ),
                ),
                (
                    "secondary_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceasecondaryquestion",
                    ),
                ),
            ],
        ),
    ]
