# Generated by Django 4.2 on 2023-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_alter_bulletpoint_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
