# Generated by Django 4.2 on 2023-10-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_criteria_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoted",
            name="quote",
            field=models.TextField(blank=True, null=True),
        ),
    ]
