# Generated by Django 4.2 on 2023-11-10 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0030_bulletpoint_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceauserquestions",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="nceauserquestions",
            name="excellence",
        ),
        migrations.RemoveField(
            model_name="nceauserquestions",
            name="merit",
        ),
    ]
