# Generated by Django 4.2 on 2023-11-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0032_bulletpoint_b_bulletpoint_g_bulletpoint_r"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletpoint",
            name="b",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="g",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="r",
            field=models.IntegerField(default=0),
        ),
    ]
