# Generated by Django 4.2 on 2023-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0033_alter_bulletpoint_b_alter_bulletpoint_g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletpoint",
            name="b",
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="g",
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="r",
            field=models.IntegerField(default=255),
        ),
    ]
