# Generated by Django 4.2 on 2023-12-03 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0035_bulletpoint_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceauserquestions",
            name="answer_html",
        ),
    ]
