# Generated by Django 4.2 on 2023-12-03 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0036_remove_nceauserquestions_answer_html"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssesmentSchedule",
        ),
    ]
