# Generated by Django 4.2 on 2023-12-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0040_assignment_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
