# Generated by Django 4.2 on 2023-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_assignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='secret_code',
            field=models.CharField(default=None, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
