# Generated by Django 4.2 on 2023-12-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_classroom_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nceauserdocument',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.assignment'),
        ),
    ]
