# Generated by Django 4.2 on 2024-01-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0042_assignment_ends_at_assignment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="secret_code",
            field=models.CharField(
                default="1", editable=False, max_length=6, unique=True
            ),
            preserve_default=False,
        ),
    ]
