# Generated by Django 4.2 on 2024-02-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_classroom_secret_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="strict",
            field=models.IntegerField(default=0),
        ),
    ]
