# Generated by Django 4.2 on 2024-01-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_nceauserdocument_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
