# Generated by Django 4.2 on 2024-02-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0044_assignment_strict"),
    ]

    operations = [
        migrations.AddField(
            model_name="nceauserdocument",
            name="started",
            field=models.BooleanField(default=False),
        ),
    ]
