# Generated by Django 4.2 on 2024-01-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
    ]
