# Generated by Django 4.2 on 2024-01-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
