# Generated by Django 4.2 on 2024-02-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0045_nceauserdocument_started"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceauserdocument",
            name="editable",
        ),
        migrations.RemoveField(
            model_name="nceauserdocument",
            name="started",
        ),
        migrations.AddField(
            model_name="nceauserdocument",
            name="status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="strict",
            field=models.IntegerField(default=2),
        ),
    ]
