# Generated by Django 4.2 on 2024-01-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_assignment_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='started', max_length=50),
        ),
    ]
