# Generated by Django 4.2 on 2024-02-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0046_remove_nceauserdocument_editable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="strict",
            field=models.BooleanField(default=False),
        ),
    ]
