# Generated by Django 4.2 on 2024-02-04 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0047_alter_assignment_strict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceauserdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nceadocument",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
