# Generated by Django 4.2 on 2024-02-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0048_alter_nceauserdocument_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceauserquestions",
            name="answer",
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
