# Generated by Django 4.2 on 2024-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nceauserdocument',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
