# Generated by Django 4.2 on 2024-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0049_alter_nceauserquestions_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceaquestion",
            name="QUESTION",
            field=models.IntegerField(editable=False),
        ),
    ]
