# Generated by Django 4.2 on 2024-02-26 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0050_alter_nceaquestion_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkedChunks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alpha", models.TextField()),
                ("beta", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceauserdocument",
                    ),
                ),
            ],
        ),
    ]
