# Generated by Django 4.2 on 2024-02-27 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0051_markedchunks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criteria",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="markedchunks",
            name="alpha",
        ),
        migrations.RemoveField(
            model_name="markedchunks",
            name="beta",
        ),
        migrations.AddField(
            model_name="markedchunks",
            name="common_questions",
            field=models.ManyToManyField(
                blank=True, related_name="chunkquestions", to="main.nceauserquestions"
            ),
        ),
        migrations.AddField(
            model_name="markedchunks",
            name="criterias",
            field=models.ManyToManyField(
                blank=True, related_name="chunkcriteria", to="main.criteria"
            ),
        ),
        migrations.AddField(
            model_name="markedchunks",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
