# Generated by Django 4.2 on 2024-02-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0053_remove_markedchunks_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedchunks",
            name="common_questions",
            field=models.ManyToManyField(
                related_name="chunkquestions", to="main.nceauserquestions"
            ),
        ),
        migrations.AlterField(
            model_name="markedchunks",
            name="criterias",
            field=models.ManyToManyField(
                related_name="chunkcriteria", to="main.criteria"
            ),
        ),
    ]
