# Generated by Django 4.2 on 2024-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0054_alter_markedchunks_common_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nceasecondaryquestion",
            name="thequestion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
