# Generated by Django 4.2 on 2024-03-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0055_nceasecondaryquestion_thequestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedchunks",
            name="common_questions",
            field=models.ManyToManyField(
                related_name="chunkquestions", to="main.nceasecondaryquestion"
            ),
        ),
    ]
