# Generated by Django 4.2 on 2024-03-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_nceauserimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nceaquestion",
            name="a3",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="a4",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="e7",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="e8",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="m5",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="m6",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="n0",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="n1",
        ),
        migrations.RemoveField(
            model_name="nceaquestion",
            name="n2",
        ),
        migrations.CreateModel(
            name="NceaQUESTIONcalc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField(default=0)),
                ("a", models.IntegerField(default=0)),
                ("m", models.IntegerField(default=0)),
                ("e", models.IntegerField(default=0)),
                (
                    "QUESTION",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.nceaquestion",
                    ),
                ),
            ],
        ),
    ]
