# Generated by Django 4.2 on 2024-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0058_remove_nceaquestion_a3_remove_nceaquestion_a4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nceaquestioncalc",
            name="a",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="nceaquestioncalc",
            name="e",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="nceaquestioncalc",
            name="m",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
