# Generated by Django 4.2 on 2024-04-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0059_alter_nceaquestioncalc_a_alter_nceaquestioncalc_e_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
