# Generated by Django 4.2 on 2024-04-07 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0060_assignment_starts_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nceaquestioncalc",
            options={"ordering": ["QUESTION", "type"]},
        ),
    ]
