# Generated by Django 4.2 on 2024-04-07 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0061_alter_nceaquestioncalc_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nceaquestioncalc",
            options={"ordering": ["QUESTION", "-type"]},
        ),
    ]
